---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: roboto-go
  namespace: roboto
  labels:
    app: roboto-go
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: roboto-go
  template:
    metadata:
      labels:
        app: roboto-go
    spec:
      containers:
      - name: roboto
        image: ghcr.io/akvanvig/roboto-go:v1
        args:
          - "--token=$(TOKEN)"
        resources:
          limits:
            cpu: 500m
            memory: 200Mi
        envFrom:
          - secretRef:
              name: roboto-secret
              optional: false
