# Default values for roboto-go.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: ghcr.io/akvanvig/roboto-go
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe: []
  # httpGet:
  #   path: /
  #   port: http
readinessProbe: []
  # httpGet:
  #   path: /
  #   port: http

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes:
  - name: roboto-config
    configMap:
      name: roboto-cm
      items:
        - key: roboto-config.yaml
          path: roboto-config.yaml

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
  - name: roboto-config
    mountPath: /opt/roboto/

nodeSelector: {}

tolerations: []

affinity: {}

roboto:
  extraCmValues: {}
  # override file for autogenerated configmap
  secretsFileName: ""
  discord:
    token: ""
  lavalink:
    replicas: 1
    port: 2333

lavalink:
  persistance: false
  storageClass: ""
  storage: "10Gi"
  javaOptions: "-Xmx6G"
  image:
    repository: "ghcr.io/lavalink-devs/lavalink"
    tag: "4"
  service:
    type: ClusterIP
    port: 2333
  livenessProbe: {}
    # httpGet:
    #   path: /
    #   port: http
  readinessProbe: {}
    # httpGet:
    #   path: /
    #   port: http
  resources: {}
  volumeMounts: []
  volumes: []
  nodeSelector: {}
  tolerations: []
  affinity: {}

  # config values passed to lavalink application.yml file:
  config:
    server:
      http2:
        enabled: true

    plugins:
      youtube:
        enabled: true
        allowSearch: true
        allowDirectVideoIds: true
        allowDirectPlaylistIds: true
        oauth:
          enabled: true
          refreshToken: ""
        clients:
          - MUSIC
          - TV
          - TVHTML5_SIMPLY
          - WEB
          - WEBEMBEDDED
          - MWEB
          - ANDROID_VR
    lavalink:
      plugins:
        - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.0"
          snapshot: false
        - dependency: "com.github.topi314.lavaqueue:lavaqueue-plugin:7b32f42"
          repository: "https://maven.topi.wtf/snapshots"
          snapshot: false
      server:
        sources:
          youtube: false
          bandcamp: false
          twitch: false
          vimeo: false
          nico: false
          http: false
          local: false
          soundcloud: true
        filters: # All filters are enabled by default
          volume: true
          equalizer: true
          karaoke: true
          timescale: true
          tremolo: true
          vibrato: true
          distortion: true
          rotation: true
          channelMix: true
          lowPass: true
        nonAllocatingFrameBuffer: false # Setting to true reduces the number of allocations made by each player at the expense of frame rebuilding (e.g. non-instantaneous volume changes)
        bufferDurationMs: 400 # The duration of the NAS buffer. Higher values fare better against longer GC pauses. Duration <= 0 to disable JDA-NAS. Minimum of 40ms, lower values may introduce pauses.
        frameBufferDurationMs: 5000 # How many milliseconds of audio to keep buffered
        opusEncodingQuality: 10 # Opus encoder quality. Valid values range from 0 to 10, where 10 is best quality but is the most expensive on the CPU.
        resamplingQuality: LOW # Quality of resampling operations. Valid values are LOW, MEDIUM and HIGH, where HIGH uses the most CPU.
        trackStuckThresholdMs: 10000 # The threshold for how long a track can be stuck. A track is stuck if does not return any audio data.
        useSeekGhosting: true # Seek ghosting is the effect where whilst a seek is in progress, the audio buffer is read from until empty, or until seek is ready.
        youtubePlaylistLoadLimit: 6 # Number of pages at 100 each
        playerUpdateInterval: 5 # How frequently to send player updates to clients, in seconds
        youtubeSearchEnabled: true
        soundcloudSearchEnabled: true
        gc-warnings: true
        #ratelimit:
        #ipBlocks: ["1.0.0.0/8", "..."] # list of ip blocks
        #excludedIps: ["...", "..."] # ips which should be explicit excluded from usage by lavalink
        #strategy: "RotateOnBan" # RotateOnBan | LoadBalance | NanoSwitch | RotatingNanoSwitch
        #searchTriggersFail: true # Whether a search 429 should trigger marking the ip as failing
        #retryLimit: -1 # -1 = use default lavaplayer value | 0 = infinity | >0 = retry will happen this numbers times
        #youtubeConfig: # Required for avoiding all age restrictions by YouTube, some restricted videos still can be played without.
        #email: "" # Email of Google account
        #password: "" # Password of Google account
        #httpConfig: # Useful for blocking bad-actors from ip-grabbing your music node and attacking it, this way only the http proxy will be attacked
        #proxyHost: "localhost" # Hostname of the proxy, (ip or domain)
        #proxyPort: 3128 # Proxy port, 3128 is the default for squidProxy
        #proxyUser: "" # Optional user for basic authentication fields, leave blank if you don't use basic auth
        #proxyPassword: "" # Password for basic authentication

    metrics:
      prometheus:
        enabled: false

    sentry:
      dsn: ""
      environment: ""

    logging:
      file:
        path: ./logs/

      level:
        root: INFO
        lavalink: INFO

      request:
        enabled: true
        includeClientInfo: true
        includeHeaders: false
        includeQueryString: true
        includePayload: true
        maxPayloadLength: 10000

      logback:
        rollingpolicy:
          max-file-size: 1GB
          max-history: 30

ollama:
  server: http://192.168.0.100:11434
  chatPath: /api/chat
  generatePath: /api/generate
  defaultPrompt:
    name: "default"
    model: "Qwen2.5"
    systemPrompt: |-
      Your name is "chat".
      You are a young man under an authoritrian regime.

      You need to follow these rules:
        - keep it short - Respond is a short and concise way.
  serverPrompts:
    239075977055961088:
      name: test-server
      systemPrompt: |-
        Mention your friend "Fredrik" at any opportunity.
  channelPrompts:
    239075977055961088:
      name: test-server beta cuck
      exclusive: true
      systemPrompt: |-
        You are a dog named "Douglas".
        You will respond with "Bjeff bjeff" and "grrrr" unless someone gives you a treat
