{{- if .Values.ytCipher.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-yt-cipher" ( include "roboto-go.name" .) }}
  labels:
    {{- include "roboto-go.labelsYtCipher" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.ytCipher.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "roboto-go.selectorLabelsYtCipher" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "roboto-go.labelsYtCipher" . | nindent 8 }}
        {{- with .Values.ytCipher.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "roboto-go.serviceAccountName" . }}
      {{- with .Values.ytCipher.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: "yt-cipher"
          {{- with .Values.ytCipher.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.ytCipher.image.repository }}:{{ .Values.ytCipher.image.tag }}"
          imagePullPolicy: {{ .Values.ytCipher.image.pullPolicy }}
          {{- with .Values.ytCipher.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.ytCipher.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.ytCipher.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.ytCipher.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.ytCipher.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.ytCipher.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ytCipher.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ytCipher.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ytCipher.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
