{{- if and .Values.ytCipher.enabled .Values.ytCipher.networkPolicy.enabled }}
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ printf "%s-yt-cipher" ( include "roboto-go.name" .) }}
spec:
  endpointSelector:
    matchLabels:
      {{- include "roboto-go.selectorLabelsYtCipher" . | nindent 6 }}
  ingress:
    - fromEndpoints:
        - matchLabels:
            {{- include "roboto-go.selectorLabelsLavalink" . | nindent 12 }}
      toPorts:
        - ports:
            - port: {{ .Values.ytCipher.service.port | quote }}
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
    - toFQDNs:
        - matchPattern: "*.youtube.com"
      toPorts:
        - ports:
            - port: "443"
{{- end }}
