{{- if and .Values.ytCipher.enabled .Values.ytCipher.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ printf "%s-yt-cipher" ( include "roboto-go.name" .) }}
spec:
  podSelector:
    matchLabels:
      {{- include "roboto-go.selectorLabelsYtCipher" . | nindent 6 }}
  policyTypes:
    - Egress
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "roboto-go.selectorLabels" . | nindent 14 }}
      ports:
        - port: {{- .Values.ytCipher.service.port }}
  egress: []
{{- end }}
