name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'main'
    tags:
      - 'v*.*.*'

permissions:
  packages: write
  contents: read

jobs:
  audit-project:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
      
    - name: Scan project
      uses: anchore/scan-action@v6
      with:
        path: "."
  build-push-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Set up docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to ghcr
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.GITHUB_TOKEN }}

    - name: Add docker metadata
      id: metadata
      uses: docker/metadata-action@v5
      with: 
        images: |
          ghcr.io/akvanvig/roboto-go
        tags: |
          type=ref,event=branch
          type=semver,pattern=v{{version}}
          type=semver,pattern=v{{major}}.{{minor}}
          type=semver,pattern=v{{major}}
          type=sha

    - name: Build and push
      uses: docker/build-push-action@v6
      with: 
        context: .
        file: cmd/roboto/Dockerfile
        push: true
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
